# Generated by Django 5.2.4 on 2025-07-22 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_user_jobapplication_user_alter_job_posted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
    ]
